[package]
name = "sort-terminal"
version = "0.1.0"
authors = ["Fernando Eckstein <fernando_eckstein@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]